apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    client.knative.dev/user-image: us-docker.pkg.dev/training-363310/cloud-run-book/hello
    run.googleapis.com/client-name: gcloud
    run.googleapis.com/client-version: 403.0.0
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/operation-id: 27ac51aa-05a2-4e49-914d-0c898d262206
    serving.knative.dev/creator: alejandro.aceituna@intelygenz.com
    serving.knative.dev/lastModifier: alejandro.aceituna@intelygenz.com
  creationTimestamp: '2023-02-21T08:27:57.987904Z'
  generation: 1
  labels:
    cloud.googleapis.com/location: europe-west4
  name: hello-world
  namespace: '382004453183'
  resourceVersion: AAX1MY74mm4
  selfLink: /apis/serving.knative.dev/v1/namespaces/382004453183/services/hello-world
  uid: ba68ea5a-c428-4bab-a299-ad18b5496c37
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '100'
        client.knative.dev/user-image: us-docker.pkg.dev/training-363310/cloud-run-book/hello
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 403.0.0
      name: hello-world-00001-poz
    spec:
      containerConcurrency: 80
      containers:
      - image: us-docker.pkg.dev/training-363310/cloud-run-book/hello
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
      serviceAccountName: 382004453183-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
status:
  address:
    url: https://hello-world-j6lupchraa-ez.a.run.app
  conditions:
  - lastTransitionTime: '2023-02-21T08:28:04.413038Z'
    status: 'True'
    type: Ready
  - lastTransitionTime: '2023-02-21T08:28:04.086706Z'
    status: 'True'
    type: ConfigurationsReady
  - lastTransitionTime: '2023-02-21T08:28:04.413038Z'
    status: 'True'
    type: RoutesReady
  latestCreatedRevisionName: hello-world-00001-poz
  latestReadyRevisionName: hello-world-00001-poz
  observedGeneration: 1
  traffic:
  - latestRevision: true
    percent: 100
    revisionName: hello-world-00001-poz
  url: https://hello-world-j6lupchraa-ez.a.run.app
